name: webhook-trigger

on:
  repository_dispatch:
    types: 
      - webhook-one
      - webhook-two

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn
      - run: yarn deploy:all
      # - run: 'yarn vercel -S vesuvio-media --confirm --token ${{ secrets.VERCEL_TOKEN }} --env [SITE_ID=${{ github.event.client_payload.siteId }}] --build-env [SITE_ID=${{ github.event.client_payload.siteId }}]'
